// Official Investor Relations (IR) Portals for NIFTY 50 companies
export const COMPANY_IR_PORTALS: Record<string, { irUrl: string; pressReleaseUrl?: string }> = {
  RELIANCE: { irUrl: 'https://www.ril.com/investor-relations', pressReleaseUrl: 'https://www.ril.com/media-releases' },
  TCS: { irUrl: 'https://www.tcs.com/investor-relations', pressReleaseUrl: 'https://www.tcs.com/newsroom' },
  HDFCBANK: { irUrl: 'https://www.hdfcbank.com/personal/about-us/investor-relations' },
  INFY: { irUrl: 'https://www.infosys.com/investors.html', pressReleaseUrl: 'https://www.infosys.com/newsroom.html' },
  ICICIBANK: { irUrl: 'https://www.icicibank.com/about-us/investor-relations' },
  BHARTIARTL: { irUrl: 'https://www.airtel.in/about-bharti/equity' },
  SBIN: { irUrl: 'https://sbi.co.in/web/investor-relations' },
  LICI: { irUrl: 'https://licindia.in/investor-relations' },
  ITC: { irUrl: 'https://www.itcportal.com/investor' },
  HINDUNILVR: { irUrl: 'https://www.hul.co.in/investor-relations' },
  LT: { irUrl: 'https://www.larsentoubro.com/corporate/investors' },
  BAJFINANCE: { irUrl: 'https://www.bajajfinserv.in/investor-relations' },
  HCLTECH: { irUrl: 'https://www.hcltech.com/investors' },
  MARUTI: { irUrl: 'https://www.marutisuzuki.com/corporate/investors' },
  SUNPHARMA: { irUrl: 'https://sunpharma.com/investors' },
  TATAMOTORS: { irUrl: 'https://www.tatamotors.com/investors' },
  KOTAKBANK: { irUrl: 'https://www.kotak.com/en/investor-relations.html' },
  TITAN: { irUrl: 'https://www.titancompany.in/investors' },
  ONGC: { irUrl: 'https://ongcindia.com/investors' },
  ADANIENT: { irUrl: 'https://www.adanienterprises.com/investors' },
  NTPC: { irUrl: 'https://ntpc.co.in/investors' },
  AXISBANK: { irUrl: 'https://www.axisbank.com/shareholders-corner' },
  TRENT: { irUrl: 'https://trentlimited.com/investor-relations' },
  BEL: { irUrl: 'https://bel-india.in/investor-relations' },
  ULTRACEMCO: { irUrl: 'https://www.ultratechcement.com/investors' },
};

