create table if not exists public.marketpulse_users (
  id text primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  salt text not null,
  created_at timestamptz not null default now()
);
create table if not exists public.marketpulse_watchlists (
  id bigint generated by default as identity primary key,
  user_id text not null references public.marketpulse_users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.marketpulse_watchlist_companies (
  id bigint generated by default as identity primary key,
  watchlist_id bigint not null references public.marketpulse_watchlists(id) on delete cascade,
  company_id integer not null,
  position integer not null default 0,
  unique (watchlist_id, company_id)
);
create index if not exists marketpulse_watchlists_user_idx on public.marketpulse_watchlists(user_id);
alter table public.marketpulse_users enable row level security;
alter table public.marketpulse_watchlists enable row level security;
alter table public.marketpulse_watchlist_companies enable row level security;
-- Server routes use SUPABASE_SERVICE_ROLE_KEY. Never expose that key to the browser.
